server:
  port: 8080

spring:
  application:
    name: kb-assistant
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.kbassistant.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
