cors:
  allowed-origins: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_base_assistant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 252629
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000

ai:
  fastapi:
    base-url: http://localhost:8000
  service:
    document:
      process-url: ${ai.fastapi.base-url}/internal/document/process
      timeout: 120000
    chat:
      ask-url: ${ai.fastapi.base-url}/internal/chat/ask
      stream-url: ${ai.fastapi.base-url}/internal/chat/ask-stream
      timeout: 60000
      stream-timeout: 180000

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcA==
  expiration: 86400000

file:
  upload-dir: D:/AI Demo/kb-assistant/data/files
